[package]
name = "hecate-protobuf"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12.4"
serde = { version = "1.0.197", features = ["derive"] }

[build-dependencies]
serde_yaml = "0.9.34"
prost-build-config = "0.6.3"
anyhow = "1.0.82"
